### ISSUE TITLE
Miscellaneous requests

### ISSUE THREAD

**Issue by zhiiiyang** [yuliadm/mixComp#2]
Hi, I am the reviewer from JOSS (https://github.com/openjournals/joss-reviews/issues/4354). could you add instructions on how to install this package from GitHub besides from CRAN? Here is an example from ggplot2. Also, could you add a branch called dev for changes? The dev branch can be merged into the main branch once reaching to a stable version. 

```
# The easiest way to get ggplot2 is to install the whole tidyverse:
install.packages("tidyverse")

# Alternatively, install just ggplot2:
install.packages("ggplot2")

# Or the development version from GitHub:
# install.packages("devtools")
devtools::install_github("tidyverse/ggplot2")
```

**Comment by yuliadm** [comment]
Hi @zhiiiyang , I've created the dev branch already. Will add the instructions in the README file in a short while!

**Comment by zhiiiyang** [comment]
@yuliadm, thank you. I also have other miscellaneous suggestions. I will summarize it below to avoid opening too many issues for only 1~2 requests at once. 

- [x] add instructions on installing it from GitHub 
- [x] move reproduction_script.R and reproduction_script.html to the vignettes folder, which is empty right now. 
- [x] create a paper folder and move paper.md and refs.bib to the folder
- [x] is figures folder the same as images folder? what is this misc folder? 
- [x] add Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

**Comment by yuliadm** [comment]
Hi @zhiiiyang Many thanks for your optimization suggestions! I've found them great and have implemented most of them (in the dev branch): 

-  added the instructions to the .md file 
- moved the reproduction files to the vignette folder
-  moved the paper files to the newly created paper folder 
- merged the figures and images folder into one.

I kept the misc folder as it contains formulae for the Documentation.md file (this contains the detailed manual for those who want to have it directly on Git without going to the vignettes).

**Comment by zhiiiyang** [comment]
@yuliadm, thank you for making the changes. I have checked the to-do list here (https://github.com/yuliadm/mixComp/issues/2#issuecomment-1119274904). One more request, could you add community guidelines for contributions in your readme.md? Once you are done, I think you can merge the current dev branch with the main branch to incorporate those changes. You may want to bump the software version.

**Comment by yuliadm** [comment]
Hi @zhiiiyang ! I have added the Community Guidelines to the readme file.
