### ISSUE TITLE
Provide some real example

### ISSUE THREAD

**Issue by Athene-ai** [yuliadm/mixComp#5]
Hi, I am the reviewer from JOSS ([#4354](https://github.com/openjournals/joss-reviews/issues/4354)). 

Is it possible to add some examples from real data?

**Comment by yuliadm** [comment]
Hi @Athene-ai. There are several examples that are using the real data (the Old faithful data, Children data, Shakespeare data and the Acidity data) which can be found in the documentation.md as well as in the vignettes. Where should I incorporate these examples? The paper.md file? I could do that if adding the R code will not affect the word count (I am not sure whether it does)... Thanks!

**Comment by Athene-ai** [comment]
@yuliadm I suggest to add them in paper.md as a comment

**Comment by yuliadm** [comment]
Dear @Athene-ai  I have added another real data example to the paper. At the moment it is not included as a comment, but hopefully it is fine.
